name: Build and Release
on: [push]
jobs:
    Create-Release:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: softprops/action-gh-release@v1
              with:
                tag_name: ${{ github.ref }}
                name: ${{ github.ref }}
                draft: false
                prerelease: false
    Build-And-Publish-Windows:
        runs-on: windows-latest
        steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-python@v2
          with:
            python-version: '3.9' 
            architecture: 'x64'
        - run: pip install -r requirements.txt
        - run: pyinstaller actiontracker.spec
        - run: powershell.exe -noexit "Compress-Archive -Path dist\AbilityTracker -DestinationPath dist\LMTsAbilityTracker.zip"
        - uses: actions/upload-release-asset@v1
          with:
            upload_url: ${{ steps.create_release.outputs.upload_url }}
            asset_path: ./dist/LMTsAbilityTracker.zip
            asset_name: LMTs-Ability-Tracker
            asset_content_type: application/zip
                