name: Build and Release
on:
    push:
        branches:
            - main
jobs:
    Create-Release:
        runs-on: ubuntu-latest
        outputs:
            asset_upload_url: ${{ steps.create_release.outputs.upload_url }}
            version_number: ${{ steps.get_version.outputs.version_number }}
        steps:
            - uses: actions/checkout@v2
            - name: Get Version
              id: get_version
              run: echo ::set-output name=version_number::$(cat version)
            - name: Create Release
              id: create_release
              uses: softprops/action-gh-release@v1
              with:
                tag_name: Release-${{ steps.get_version.outputs.version_number }}
                name: ${{ steps.get_version.outputs.version_number }}
                draft: false
                prerelease: false
    Build-And-Publish-Windows:
        runs-on: windows-latest
        needs: Create-Release
        steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-python@v2
          with:
            python-version: '3.9'
            architecture: 'x64'
        - run: pip install -r requirements.txt
        - run: pyinstaller actiontracker.spec
        - run: powershell.exe -noexit "Compress-Archive -Path dist\AbilityTracker\* -DestinationPath dist\LMTsAbilityTracker.zip"
        - uses: shogo82148/actions-upload-release-asset@v1
          with:
            upload_url: ${{ needs.Create-Release.outputs.asset_upload_url }}
            asset_path: ./dist/LMTsAbilityTracker.zip
            asset_name: LMTs-Ability-Tracker-${{ needs.Create-Release.outputs.version_number }}-WIN-x64.zip
            asset_content_type: application/zip
#    Build-And-Publish-Mac-Intel:
#        runs-on: macos-latest
#        needs: Create-Release
#        steps:
#        - uses: actions/checkout@v2
#        - uses: actions/setup-python@v2
#          with:
#            python-version: '3.9'
#            architecture: 'x64'
#        - run: pip install -r requirements.txt
#        - run: pyinstaller actiontracker.spec
#        - run: zip -vr LMTsAbilityTracker.zip dist/AbilityTracker/
#        - uses: shogo82148/actions-upload-release-asset@v1
#          with:
#            upload_url: ${{ needs.Create-Release.outputs.asset_upload_url }}
#            asset_path: ./LMTsAbilityTracker.zip
#            asset_name: LMTs-Ability-Tracker-${{ needs.Create-Release.outputs.version_number }}-MacOS-x64.zip
#            asset_content_type: application/zip
#    Build-And-Publish-Linux:
#        runs-on: ubuntu-latest
#        needs: Create-Release
#        steps:
#        - uses: actions/checkout@v2
#        - uses: actions/setup-python@v2
#          with:
#            python-version: '3.9'
#            architecture: 'x64'
#        - run: pip install -r requirements.txt
#        - run: pyinstaller actiontracker.spec
#        - run: zip -r LMTsAbilityTracker.zip . -i /dist/AbilityTracker
#        - uses: shogo82148/actions-upload-release-asset@v1
#          with:
#            upload_url: ${{ needs.Create-Release.outputs.asset_upload_url }}
#            asset_path: ./LMTsAbilityTracker.zip
#            asset_name: LMTs-Ability-Tracker-${{ needs.Create-Release.outputs.version_number }}-linux-x64.zip
#            asset_content_type: application/zip
